(() => {
 'use strict';const $=id=>document.getElementById(id),key='nsi-python-lab-v1:';
 let activity=new URLSearchParams(location.search).get('activite')||'bataille';if(!STARTERS[activity])activity='bataille';
 let editor,loading=false,busy=false,worker=null,cancelled=false,finishCurrent=null,consoleLength=0;
 if(window.ace){ace.config.set('basePath','vendor/ace');editor=ace.edit('editor');editor.setTheme('ace/theme/textmate');editor.session.setMode('ace/mode/python');editor.session.setUseWorker(false);editor.session.setTabSize(4);editor.session.setUseSoftTabs(true);editor.setOptions({fontSize:15,showPrintMargin:false,wrap:true});editor.commands.addCommand({name:'runPython',bindKey:{win:'Ctrl-Enter',mac:'Command-Enter'},exec:()=>run('run')});}
 else{$('editor').hidden=true;$('fallback').hidden=false;}
 const get=()=>editor?editor.getValue():$('fallback').value;
 function set(value){loading=true;if(editor)editor.setValue(value,-1);else $('fallback').value=value;loading=false;}
 function save(){if(loading)return;try{localStorage.setItem(key+activity,get());$('save-status').textContent='✓ Brouillon sauvegardé sur ce navigateur.';}catch{$('save-status').textContent='Sauvegarde locale indisponible : exporte ton fichier .py.';}}
 if(editor)editor.session.on('change',save);else $('fallback').addEventListener('input',save);
 function showTests(){const box=$('test-details');box.replaceChildren();for(const level of ['unit','full'])for(const test of TESTS[activity][level]){const d=document.createElement('details'),s=document.createElement('summary'),pre=document.createElement('pre');s.textContent=(level==='unit'?'Unitaire · ':'Complet · ')+test.name;pre.textContent=test.code;d.append(s,pre);box.append(d);}}
 function load(){let value=STARTERS[activity];try{value=localStorage.getItem(key+activity)??value;$('save-status').textContent='Brouillon local ou squelette chargé.';}catch{$('save-status').textContent='Stockage indisponible : pense à exporter.';}set(value);$('activity').value=activity;$('activity-note').textContent=activity==='snake'?'Snake : fonctions algorithmiques uniquement. Tkinter n’est pas disponible dans le navigateur ; conserve le programme original pour son interface sur ordinateur.':'Complète les TODO puis lance les tests unitaires, avant les scénarios complets.';$('back').href='index.html#'+(activity==='escape_nsi'?'escape':activity);history.replaceState(null,'','?activite='+activity);$('console').textContent='';$('results').replaceChildren();showTests();}
 $('activity').onchange=()=>{save();activity=$('activity').value;load();};
 function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'text/x-python;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 $('export').onclick=()=>download(activity==='snake'?'snake_algorithmes.py':activity+'.py',get());
 function approve(message){return new Promise(resolve=>{const dialog=$('replace-dialog');$('replace-message').textContent=message;dialog.returnValue='cancel';dialog.addEventListener('close',()=>resolve(dialog.returnValue==='replace'),{once:true});dialog.showModal();});}
 $('reset').onclick=async()=>{if(await approve('Le squelette remplacera ton brouillon actuel pour cette activité.')){set(STARTERS[activity]);save();}};
 $('import').onclick=()=>$('file').click();
 $('file').onchange=async()=>{const file=$('file').files[0];$('file').value='';if(!file)return;if(!file.name.toLowerCase().endsWith('.py')||file.size>200000){$('save-status').textContent='Choisis un fichier .py UTF-8 de moins de 200 ko.';return;}const selected=activity;const value=await file.text();if(selected!==activity)return;if(await approve(`Importer ${file.name} à la place du brouillon actuel ?`)){set(value.replace(/^\uFEFF/,''));save();$('save-status').textContent=`${file.name} importé. Aucun code n’a été exécuté.`;}};
 function controls(value){busy=value;$('activity').disabled=value;$('import').disabled=value;$('reset').disabled=value;$('stop').disabled=!value;document.querySelectorAll('[data-execute]').forEach(b=>b.disabled=value||location.protocol==='file:');if(editor)editor.setReadOnly(value);else $('fallback').readOnly=value;}
 function append(text){if(consoleLength>=20000)return;const part=text.slice(0,20000-consoleLength);consoleLength+=part.length;$('console').textContent+=part;$('console').scrollTop=$('console').scrollHeight;}
 function execute(source,test,testing){return new Promise(resolve=>{let timer;const w=new Worker('atelier-worker.js');worker=w;let settled=false;const done=result=>{if(settled)return;settled=true;clearTimeout(timer);w.terminate();if(worker===w)worker=null;finishCurrent=null;resolve(result);};finishCurrent=done;timer=setTimeout(()=>done({ok:false,error:'Chargement Python trop long (60 s). Vérifie les fichiers locaux et le serveur.'}),60000);w.onmessage=({data})=>{if(data.type==='output')append(data.text);if(data.type==='running'){clearTimeout(timer);$('runtime-status').textContent=testing?'Test Python en cours…':'Programme en cours…';timer=setTimeout(()=>done({ok:false,error:'Délai de 10 secondes dépassé : recherche une boucle infinie ou un cas d’arrêt manquant.'}),10000);}if(data.type==='done')done(data);};w.onerror=e=>done({ok:false,error:e.message||'Impossible de charger Python. Ouvre la page via HTTP(S).'});w.postMessage({source,test,testing,stdin:$('stdin').value});});}
 async function run(level){if(busy||location.protocol==='file:')return;save();cancelled=false;controls(true);$('console').textContent='';consoleLength=0;$('results').replaceChildren();$('runtime-status').textContent='Chargement de Python local…';const source=get();let passed=0,total=0;
 try{if(level==='run'){const r=await execute(source,'',false);if(!r.ok)append('\n'+r.error);$('runtime-status').textContent=cancelled?'Exécution arrêtée.':r.ok?'Exécution terminée.':'Exécution en erreur.';}
 else{const tests=TESTS[activity][level];for(const test of tests){if(cancelled)break;append('\n── '+test.name+' ──\n');$('runtime-status').textContent=`Chargement du test ${total+1}/${tests.length}…`;const r=await execute(source,test.code,true);if(cancelled)break;total++;if(r.ok)passed++;const row=document.createElement('article');row.className='test-result'+(r.ok?' pass':'');const title=document.createElement('h3');title.textContent=(r.ok?'✓ ':'✗ ')+test.name;row.append(title);if(!r.ok){const pre=document.createElement('pre');pre.textContent=r.error;row.append(pre);} $('results').append(row);}$('runtime-status').textContent=cancelled?`Tests arrêtés : ${total}/${tests.length} exécutés.`:`${passed}/${tests.length} tests réussis. ${passed===tests.length?'Compare aussi avec tes propres essais.':'Lis les erreurs et complète les fonctions concernées.'}`;}}
 catch(e){$('runtime-status').textContent='Erreur de chargement : '+e.message;}finally{controls(false);}}
 $('run').onclick=()=>run('run');$('unit').onclick=()=>run('unit');$('full').onclick=()=>run('full');$('stop').onclick=()=>{cancelled=true;if(finishCurrent)finishCurrent({ok:false,error:'Arrêt demandé.'});};
 if(location.protocol==='file:')$('local-warning').hidden=false;load();controls(false);
})();
